name: ASP.NET Core CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Package NuGet
      run: dotnet pack -c Release -o out
    - name: Publish Website
      run: dotnet publish src/QMS.Web -o publish/QMS.Web -c Release
    - name: Publish Nuget to GitHub registry
      run: dotnet nuget push ./out/**/*.* -s https://api.nuget.org/v3/index.json -k ${NUGET_TOKEN}  
      env:
        NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }} 
    - name: Deploy to app service
      uses: azure/webapps-deploy@v1
      with:
        app-name: qms4-dev
        package: publish/QMS.Web
        publish-profile: ${{ secrets.qms4devpublish }}
