name: Push NuGet packages

on: [repository_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Package NuGet
      run: dotnet pack -c Release -o out
    - name: Publish Nuget to GitHub registry
      run: dotnet nuget push ./out/**/*.* -s https://api.nuget.org/v3/index.json -k ${NUGET_TOKEN}
      env:
        NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }} 